name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      # 🔥 CLEANUP BACKEND (VERY IMPORTANT)
      - name: Delete S3 Bucket
        run: aws s3 rb s3://rwa-terraform-state-123 --force

      - name: Delete DynamoDB Lock Table
        run: aws dynamodb delete-table --table-name terraform-locks
