name: Deploy DEV

on:
  push:
    branches: ["dev"]

  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ AWS Login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build CSV Lambda ZIP
        run: |
          mkdir -p infra/build
          cd lambdas
          zip -r csv_lambda.zip csv_import
          mv csv_lambda.zip ../infra/build/

      - name: Verify ZIP
        run: |
          ls -R infra/build
          
      # ✅ Terraform Install
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ✅ Init
      - name: Terraform Init
        run: |
          cd infra
          terraform init

      # ✅ Workspace
      - name: Select Workspace
        run: |
          cd infra
          terraform workspace select dev || terraform workspace new dev

      # ✅ Plan
      - name: Terraform Plan
        run: |
          cd infra
          terraform plan

      # ✅ Apply / Destroy
      - name: Terraform Apply or Destroy
        run: |
          cd infra
          ACTION="${{ github.event.inputs.action || 'apply' }}"
          if [ "$ACTION" = "destroy" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
